### ISSUE TITLE
Import CSV format

### ISSUE THREAD

**Issue by bestia-dev** [dsolonenko/financisto#80]
What is the format for importing csv? 
Is it similar to the exported csv?

**Comment by klawdhfzasjhaa** [comment]
Basically yes. Simply check, what settings you used in the export and the apply them to the import. I have already done this in the past. No problems at all.

Be sure you split the export to seperate files first, one file per account. You have to choose an account in the import dialog. Otherwise transactions of **all** your accounts will be imported to the selected **one**.
